### ISSUE TITLE
Duplicate button doesn't copy the field unless you rename and save it

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/woocommerce-product-addon#127]
### Description

When viewing the fields that are already added to a group, there is a duplicate button available.

I expected that clicking on it will duplicate the current field and eventually rename it automatically by adding _1, or _copy in its name. The button currently opens a pop-up with the data of the same field saved, allowing you to rename and save to duplicate it.

### Step-by-step reproduction instructions

1. Create a new group
2. Add a field there - it can be anything, I tested with Image Dropdown
3. Save it and check the group
4. Click on the duplicate button for the field added in the previous step
5. You will see it doesn't duplicate it immediately

### Screenshots, screen recording, code snippet or Help Scout ticket

Video about the issue: https://vertis.d.pr/v/P711Mz

Reported here: https://secure.helpscout.net/conversation/2200526621/363916?folderId=212390

### Environment info

https://pastebin.com/MAi4txmE

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @stefan-cotitosu,

I've added some changes to automatically generate data-name when the user clicks on the clone button.
Please check with this PR https://github.com/Codeinwp/woocommerce-product-addon/pull/130 and let me know if you have any issues.

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tested the PR and here is what i found:

- [ ] If i want to make more duplicates, i have to always clone the last item, because cloning the initial one won't detect that there already are duplicates in place and will use an existing id https://vertis.d.pr/v/RjOPXj

- [ ] There is a weird behaviour when the field already contains numbers in its name https://vertis.d.pr/v/UP27bk I guess it would be better to change the mechanism and always append the clone number at the end of the id. Also, if the current id is testfield999, the cloned one should be something like testfield999_1 or testfield999(1)

**Comment by girishpanchal30** [comment]
Hey @irinelenache,

I've added some new improvements, can you please check with the latest commit?

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Now the duplicating mechanism isn't working at all for me and i'm getting an error in console everytime i hit the duplicate button https://vertis.d.pr/v/Ba2N76

**Comment by girishpanchal30** [comment]
@irinelenache Fixed, please check with the latest commit.

**Comment by irinelenache** [comment]
@girishpanchal30 Tested again and now the mechanism works fine, thank you 🚀
